### ISSUE TITLE
Support for Laravel 5.4

### ISSUE THREAD

**Issue by ligne13** [micheleangioni/laravel-js-lang-converter#11]
Hi,
I upgraded to Laravel 5.4 and your package returns an error :

[Symfony\Component\Debug\Exception\FatalThrowableError]              
  Call to undefined method Illuminate\Foundation\Application::share()

located in michele-angioni/laravel-js-lang-converter/src/MicheleAngioni/LaravelJsLangConverter/LaravelJsLangConverterServiceProvider.php:38

Any idea how to fix this ?

thanks

**Comment by micheleangioni** [comment]
Yeah, the share() method has been removed.
I'll try to fix it this evening.

**Comment by ligne13** [comment]
OK thanks. This was urgent to me, so I switched to Mariuzzo's package (https://github.com/rmariuzzo/laravel-js-localization) which actually does the same thing as yours. I can't remember why I chose your package in the past, but today I think both packages are exactly the same. Unless you can explain the differences ?

thanks

**Comment by micheleangioni** [comment]
Time ago I hard forked the Mariuzzo's package because it had some blocking and urgent problems for me, but I don't remember exactly (maybe indeed Laravel version upgrade?). I added object support syntax in the lang files, but maybe nowadays also Mariuzzo's package supports it.

Feel free to use which one you prefer, I want to keep this one because I wasn't satisfied with the support at the time (no idea how it is now) and the only thing that I guarantee is to fix problems reported by users asap :)
