### ISSUE TITLE
compability of this projet with angularjs

### ISSUE THREAD

**Issue by hunter686** [micheleangioni/laravel-js-lang-converter#3]
@micheleangioni 
hello, thanks for this awesome projet!  It's neally exactly the same i am searching for a long time. Just want to know if you have tried to use this in a projet angularJS/Laravel5?  

I am just thinking if it would be possible to generate a file .js which could be usef for angular-translate or angular gettext?

**Comment by micheleangioni** [comment]
Hi @hunter686 , I'm glad you find this useful.
About angular, I'm sorry but since I do not use it, I've never tried this in an angularJS/Laravel5 project .
However I regularly use it with [VueJs](http://vuejs.org/) .

Generally speaking, once you generated the js file, you can import it with a simple script tag in the view

```
<script type="text/javascript" src="/path/to/your/lang.js" ></script>
```

to make it available to all js code.
Or directly try with a `require` in your js code, in order to use it.

**Comment by hunter686** [comment]
@micheleangioni  Thanks for your answer! I guess i will have to understand this projet and make it generate some file like this one

// locale-en.json
`{
  "HEADLINE": "What an awesome module!",
  "PARAGRAPH": "Srsly!",
  "PASSED_AS_TEXT": "Hey there! I'm passed as text value!",
  "PASSED_AS_ATTRIBUTE": "I'm passed as attribute value, cool ha?",
  "PASSED_AS_INTERPOLATION": "Beginners! I'm interpolated!",
  "VARIABLE_REPLACEMENT": "Hi {{name}}",
  "BUTTON_LANG_DE": "German",
  "BUTTON_LANG_EN": "English"
}`

**Comment by micheleangioni** [comment]
@hunter686 You are welcome :)
